// <auto-generated />
using System;
using GrapQL.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrapQL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210511042856_sp-GetAllOwner")]
    partial class spGetAllOwner
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrapQL.Model.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("29f2f9d2-8a53-49c0-8352-723646c7c9d5"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("9ab6c46d-2282-4f24-8c86-28808389feeb"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d2ec67a0-e28c-4b8b-b7c1-8a1ef2a1c931"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("5425d31c-49b4-4862-92cd-3f6f3f1b1007"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("16891c86-8435-4b32-8cb0-be8997a504d5"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("5425d31c-49b4-4862-92cd-3f6f3f1b1007"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("GrapQL.Model.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9ab6c46d-2282-4f24-8c86-28808389feeb"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("5425d31c-49b4-4862-92cd-3f6f3f1b1007"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("GrapQL.Model.Account", b =>
                {
                    b.HasOne("GrapQL.Model.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("GrapQL.Model.Owner", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
